ALTER TABLE "User"
ADD COLUMN "jobsCreatedCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "resumesCompletedCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "resumeInFlightCount" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Resume"
ADD COLUMN "quotaReservationActive" BOOLEAN NOT NULL DEFAULT false;
